
export const DB_HOST_KEY = 'DB_HOST';
export const DB_PORT_KEY = 'DB_PORT';
export const DB_USERNAME_KEY = 'DB_USERNAME';
export const DB_PASSWORD_KEY = 'DB_PASSWORD';
export const DB_DATABASE_KEY = 'DB_DATABASE';

export const GOOGLE_CLIENT_ID_KEY = 'GOOGLE_CLIENT_ID';
export const GOOGLE_CLIENT_SECRET_KEY = 'GOOGLE_SECRET_ID';
export const GOOGLE_REDIRECT_URL_KEY = 'GOOGLE_REDIRECT_URL';